apiVersion: apps/v1
kind: Deployment
metadata:
  name: yogishow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yogishow
  template:
    metadata:
      labels:
        app: yogishow
    spec:
      containers:
      - name: yogishow
        image: fflament/yogishow:latest
        ports:
        - containerPort: 8080
