apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contour
  namespace: {{ .Values.spec.destination.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: contour
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: contour
  syncPolicy:
    automated: {}
    syncOptions:
    - ApplyOutOfSyncOnly=true        
    - CreateNamespace=true
