apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloapp
  template:
    metadata:
      labels:
        app: helloapp
    spec:
      containers:
      - name: helloapp
        image: fflament/helloapp:latest
        env:
        - name: HELLO_MESSAGE
          value: {{ .Values.message }}
        ports:
        - containerPort: 8080
